// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Spotimote
{
    internal sealed partial class Vsix
    {
        public const string Id = "140b409e-01d3-44e3-9ad7-5a56ae74dc25";
        public const string Name = "Spotimote";
        public const string Description = @"Remotely control Spotify from right inside VS 2022";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Daniel Sandberg";
        public const string Tags = "";
    }
}
