// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StudioSpotify
{
    internal sealed partial class Vsix
    {
        public const string Id = "d83e0b89-3864-4036-98f5-8dc5cdb58c59";
        public const string Name = "Studio Spotify";
        public const string Description = @"Lets you control Spotify from right inside Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "BDSoftware";
        public const string Tags = "";
    }
}
