// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StudioSpotify
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string StudioSpotifyString = "51443615-a922-4a5c-8f37-7e9bb4ab44ca";
        public static Guid StudioSpotify = new Guid(StudioSpotifyString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int StudioSpotifyCommand = 0x0100;
    }
}