// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Remotify
{
    internal sealed partial class Vsix
    {
        public const string Id = "ADF07379-FA2A-4442-92DC-21190FB583CF";
        public const string Name = "Remotify";
        public const string Description = @"Lets you control Spotify from right inside Visual Studio";
        public const string Language = "en-US";
        public const string Version = "0.9.1";
        public const string Author = "BDSoftware";
        public const string Tags = "";
    }
}
