// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Remotify
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RemotifyString = "51443615-a922-4a5c-8f37-7e9bb4ab44ca";
        public static Guid Remotify = new Guid(RemotifyString);

        public const string guidRemotifyPackageCmdSetString = "70feb9ed-ff71-4c44-9567-6523b93dccc3";
        public static Guid guidRemotifyPackageCmdSet = new Guid(guidRemotifyPackageCmdSetString);

        public const string guidImagesString = "3be6a221-51ca-46a5-b524-b9707950b5c1";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RemotifyCommand = 0x0100;
        public const int MyMenuGroup = 0x1020;
        public const int cmdidCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}